- name: "Create user and send ssh key"
  gather_facts: false
  hosts: "all"
  become: true
  tasks:
    - name: Add the user 'user1' with primary group of 'admin'
      ansible.builtin.user:
        name: user1
        comment: user 1
        group: adm
    - name: Make .ssh user dir
      file:
        path: /home/user1/.ssh
        state: directory
    - name: Copy ssh key pub
      ansible.builtin.copy:
        src: files/id_user1.pub
        dest: /home/user1/.ssh/id_rsa.pub
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: user1
        state: present
        key: "{{ lookup('file', 'files/id_user1.pub') }}"