- name: "Create superuser group and add user1 and user2"
  gather_facts: false
  hosts: "all"
  become: true
  tasks:
    - name: Ensure group "superuser" exists
      ansible.builtin.group:
        name: superuser
        state: present
    - name: Add the user 'user2\user3' with primary group of 'admin'
      ansible.builtin.user:
        name: "{{ item }}"
        group: superuser
      loop:
        - user2
        - user3
    - name: Validate the sudoers file before saving
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%superuser ALL='
        line: '%superuser ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s
