- hosts: nginx
  gather_facts: false
  become: yes
  roles:
    - role: users
      user: "user123"
      group: "adm"
      key_pub: "files/id_user1.pub"
    - role: nginx
      server_name: "Nginx web server"
      app_work_dir: "/var/www/html"
      php_server: "192.168.0.5"
      php_port: "9000"

- hosts: php
  gather_facts: false
  become: yes
  roles:
    - role: users
      user: "user123"
      group: "adm"
      key_pub: "files/id_user1.pub"
    - role: php
      php_version: "8.1"
      php_port: "9000"
      allow_client: "192.168.0.6"