- hosts: "all"
  become: yes
  roles:
    - role: nginx_php
      server_name: "Nginx web server test"
      #app_work_dir: "/var/www/html"
      app_work_dir: "/opt/nginx/ansible"
      php_version: "8.1"